[project]
name = "pyxmas"
version = "0.0.0"
description = "An xmas python project"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "numpy>=1.24.4",
    "pandas>=2.0.3",
    "plotly>=5.24.1",
    "polars>=1.8.2",
]
